sudo: required
language: bash
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install docker
script:
- ./support/ci.sh
notifications:
  slack:
    secure: FjTKlrpHSKlUktFSf9W6ANmxWujelaN4bPRletBXkNwmZYwpqN1YC4lFwS16X0J6kNyvHGRva018YsUMtwI/FXtHH3YliyxCivmEoeAlZa+jMdy16pmBGhxo+mPC92SnHt1DhXfQUTstWw3h+Lq2F2MfwrB8k+nVBFJjfrF8HY0=
