[package]
name = "bldr"
version = "0.1.0"
authors = ["Adam Jacob <adam@chef.io>"]
exclude = ["packages/**/*"]

[lib]
name = "bldr"
path = "src/bldr/lib.rs"

[[bin]]
name = "bldr"
doc = false

[[test]]
name = "functional"

[dependencies]
docopt = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"
ansi_term = "*"
hyper = "*"
tempdir = "*"
toml = "*"
regex = "*"
libc = "*"
url = "*"
inotify = "*"
fnv = "*"
iron = "*"
router = "*"
mount = "*"
staticfile = "*"
time = "*"

[dependencies.wonder]
path = "./vendor/wonder"

[dependencies.mustache]
git = "https://github.com/adamhjk/rust-mustache"
branch = "fallback_on_missing_extension"

[profile.release]
lto = true
