[package]
name = "bldr"
version = "0.1.0"
authors = ["Adam Jacob <adam@chef.io>"]
exclude = ["packages/**/*"]

[lib]
name = "bldr"
path = "src/bldr/lib.rs"

[[bin]]
name = "bldr"
doc = false

[[test]]
name = "bldr-test"

[dependencies]
docopt = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"
ansi_term = "*"
hyper = "*"
tempdir = "*"
toml = "*"
regex = "*"
libc = "*"

[dependencies.mustache]
git = "https://github.com/adamhjk/rust-mustache"
branch = "fallback_on_missing_extension"
