shell:
  image: habitat/devshell
  privileged: true
  volumes:
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - cache_src
    - cache_keys
    - cargo

cache_src:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/cache/src

cache_keys:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/cache/keys

cargo:
  image: tianon/true
  command: /true
  volumes:
    - /cargo-cache
