bldr:
  image: chef/bldr
  privileged: true
  volumes:
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - installed
    - cache_keys
    - cargo
  links:
    - etcd

package:
  image: chef/bldr
  privileged: true
  volumes:
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - installed
    - cache_src
    - cache_pkgs
    - cache_keys
    - cargo
  links:
    - etcd

base:
  image: bldr
  links:
    - etcd

etcd:
  container_name: bldr_etcd_1
  image: quay.io/coreos/etcd:latest
  ports:
    - "4001:4001"
    - "7001:7001"
  command: "-cors='*' -listen-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001' -advertise-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001'"

cache_src:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/cache/src

cache_pkgs:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/cache/pkgs

cache_keys:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/cache/keys

installed:
  image: tianon/true
  command: /true
  volumes:
    - /opt/bldr/pkgs

cargo:
  image: tianon/true
  command: /true
  volumes:
    - /bldr-cargo-cache
