bldr:
  image: chef/bldr
  environment:
    DOCKER_CERT_PATH: "/docker-certs"
    DOCKER_TLS_VERIFY: 1
  volumes:
    - .:/src
    - "~/.docker/machine/certs:/docker-certs"
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-keys-cache"
    - "bldr-installed-cache"
  links:
    - etcd

package:
  image: chef/bldr
  privileged: true
  environment:
    DOCKER_CERT_PATH: "/docker-certs"
    DOCKER_TLS_VERIFY: 1
  volumes:
    - .:/src
    - "~/.docker/machine/certs:/docker-certs"
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-pkg-cache"
    - "bldr-keys-cache"
    - "bldr-src-cache"
    - "bldr-installed-cache"
  links:
    - etcd

base:
  image: bldr
  links:
    - etcd

etcd:
  image: quay.io/coreos/etcd:latest
  ports:
    - "4001:4001"
    - "7001:7001"
  command: "-cors='*' -listen-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001' -advertise-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001'"
