bldr:
  image: chef/bldr
  privileged: true
  volumes:
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-keys-cache"
    - "bldr-installed-cache"
  environment:
    - http_proxy=$http_proxy
    - https_proxy=$https_proxy
  links:
    - etcd

package:
  image: chef/bldr
  privileged: true
  volumes:
    - .:/src
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-pkg-cache"
    - "bldr-keys-cache"
    - "bldr-src-cache"
    - "bldr-installed-cache"
  environment:
    - http_proxy=$http_proxy
    - https_proxy=$https_proxy
  links:
    - etcd

base:
  image: bldr
  environment:
    - http_proxy=$http_proxy
    - https_proxy=$https_proxy
  links:
    - etcd

etcd:
  container_name: bldr_etcd_1
  image: quay.io/coreos/etcd:latest
  ports:
    - "4001:4001"
    - "7001:7001"
  command: "-cors='*' -listen-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001' -advertise-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001'"
