bldr:
  image: chef/bldr
  volumes:
    - .:/src
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-keys-cache"
    - "bldr-installed-cache"
  links:
    - repo

repo:
  image: nginx
  ports:
    - "8080:80"
  volumes_from:
    - "bldr-pkg-cache"
    - "bldr-keys-cache"
  command: bash -c 'rm -rf /usr/share/nginx/html; ln -s /opt/bldr/cache /usr/share/nginx/html; exec nginx -g "daemon off;"'

package:
  image: chef/bldr
  volumes:
    - .:/src
  volumes_from:
    - "bldr-cargo-cache"
    - "bldr-pkg-cache"
    - "bldr-keys-cache"
    - "bldr-src-cache"
    - "bldr-installed-cache"

base:
  build: ./bldr-base
  links:
    - repo
  command: ["install", "redis"]
