[package]
name = "habitat-launcher-client"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>"]

[dependencies]
bincode = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat-launcher-protocol = { git = "https://github.com/habitat-sh/protocols.git" }
ipc-channel = { git = "https://github.com/habitat-sh/ipc-channel", branch = "hbt-windows" }
libc = "*"
protobuf = "*"
serde = "*"
