auth_token = "{{cfg.auth_token}}"
auto_publish = {{cfg.auto_publish}}
data_path = "{{pkg.svc_data_path}}"
log_path = "{{cfg.log_path}}"
bldr_channel = "{{cfg.bldr_channel}}"
features_enabled = "{{cfg.features_enabled}}"
{{~#eachAlive bind.depot.members as |member|}}
{{~#if @first}}
bldr_url = "{{member.cfg.url}}"
{{~/if}}
{{~/eachAlive}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

[jobsrv]
host = "{{bind.jobsrv.first.sys.ip}}"
port = {{bind.jobsrv.first.cfg.worker_port}}
log_port = {{bind.jobsrv.first.cfg.log_port}}
